name: Main

on:
  push:
    branches: [master, master-dev]
  pull_request:
    branches: [master, master-dev]
  workflow_dispatch:

jobs:
  BuildDesktop:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: .\setup\windows.bat

      - name: Build
        run: |
          echo Building for Windows...
          REM Replace with actual build command
          # Example: haxelib run lime build windows -release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: H-Slice_0.2.1_Windows
          path: export\release\windows\bin\*
