name: Main

on:
  push:
    branches: [ master, master-dev ]
  pull_request:
    branches: [ master, master-dev ]
  workflow_dispatch:

jobs:
  BuildDesktop:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          .\setup\windows.bat
        shell: cmd

      - name: Skip SScript setup mode
        run: echo oy9:showMacroty8:loopCosti25y10:includeAllfg >> %USERPROFILE%\settings.cocoa
        shell: cmd

      - name: Create Version Tag
        run: echo %GITHUB_RUN_ID% > VERSION
        shell: cmd

      - name: Build
        run: haxelib run lime build windows --app-version="4.0.0-%GITHUB_RUN_ID%" -D officialBuild
        shell: cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: H-Slice_0.2.1_Windows
          path: export\release\windows\bin\*
